# Generated by Django 3.2.4 on 2021-06-16 23:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileStorageSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('filePath', models.FileField(upload_to='F:/School/Summer2021/Independent Study/media/files')),
                ('fileName', models.CharField(default='NAME', max_length=50)),
                ('fileType', models.CharField(default='TYPE', max_length=50)),
                ('fileNote', models.TextField(default='Extra Info')),
                ('fileURL', models.CharField(default='OOPS', max_length=50)),
                ('size', models.CharField(default='0', max_length=50)),
                ('uploadDate', models.CharField(default='DATE', max_length=50)),
                ('public', models.BooleanField()),
                ('uploadedBy', models.IntegerField(default=-1)),
            ],
        ),
    ]
