# Generated by Django 3.2.4 on 2021-06-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileStorageSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.FileField(upload_to='F:/School/Summer2021/Independent Study/media/files')),
                ('fileName', models.CharField(default='NAME', max_length=50)),
                ('fileType', models.CharField(default='TYPE', max_length=50)),
                ('fileNote', models.TextField(default='Extra Info')),
                ('fileURL', models.CharField(default='OOPS', max_length=50)),
                ('size', models.CharField(default='0', max_length=50)),
                ('uploadDate', models.CharField(default='DATE', max_length=50)),
                ('public', models.BooleanField()),
                ('uploadedBy', models.IntegerField()),
            ],
        ),
    ]
