# Generated by Django 3.2.3 on 2021-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50)),
                ('fileType', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('uploadDate', models.DateField()),
                ('modifyDate', models.DateField()),
                ('visibility', models.BooleanField()),
            ],
        ),
    ]
