# Generated by Django 3.2.4 on 2021-06-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='pathToFile',
            field=models.CharField(default='NULL PATH', max_length=100),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='fileName',
            field=models.CharField(default='NULL NAME', max_length=50),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='fileType',
            field=models.CharField(default='NULL TYPE', max_length=50),
        ),
    ]
