# Generated by Django 3.2.4 on 2021-07-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210715_1318'),
        ('fileStorage', '0002_alter_filestorageschema_uploaddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorageschema',
            name='groups',
            field=models.ForeignKey(default='GROUP_KEY', on_delete=django.db.models.deletion.CASCADE, to='User.group'),
        ),
    ]
