# Generated by Django 3.2.4 on 2021-06-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0002_auto_20210602_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fileStorage',
            new_name='fileStorageSchema',
        ),
    ]
