# Generated by Django 3.2.4 on 2021-06-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0004_filestorageschema_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorageschema',
            name='fileName',
        ),
        migrations.AlterField(
            model_name='filestorageschema',
            name='filePath',
            field=models.FilePathField(default='', path='F:/School/Summer2021/Independent Study/media/files'),
        ),
    ]
