# Generated by Django 3.2.4 on 2021-06-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0005_auto_20210603_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorageschema',
            name='fileName',
            field=models.CharField(default='NULL NAME', max_length=50),
        ),
    ]
