# Generated by Django 3.2.4 on 2021-07-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0006_filestorageschema_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorageschema',
            name='fileName',
            field=models.CharField(default='NAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='filestorageschema',
            name='fileURL',
            field=models.CharField(default='OOPS', max_length=150),
        ),
        migrations.AlterField(
            model_name='filestorageschema',
            name='size',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
