# Generated by Django 3.2.4 on 2021-06-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0006_filestorageschema_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filestorageschema',
            old_name='visibility',
            new_name='public',
        ),
        migrations.AlterField(
            model_name='filestorageschema',
            name='size',
            field=models.IntegerField(default='0'),
        ),
    ]
