# Generated by Django 3.2.4 on 2021-06-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0008_alter_filestorageschema_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorageschema',
            name='filePath',
            field=models.FileField(upload_to='books/pdfs/'),
        ),
    ]
