# Generated by Django 3.2.4 on 2021-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0009_alter_filestorageschema_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorageschema',
            name='fileNote',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
