# Generated by Django 3.2.4 on 2021-06-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0011_alter_filestorageschema_filenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorageschema',
            name='fileNote',
            field=models.TextField(default='Extra Info'),
        ),
        migrations.AlterField(
            model_name='filestorageschema',
            name='uploadDate',
            field=models.CharField(default='NULL TYPE', max_length=50),
        ),
    ]
