# Generated by Django 3.2.4 on 2021-06-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0013_remove_filestorageschema_modifydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorageschema',
            name='pathToFile',
        ),
        migrations.AlterField(
            model_name='filestorageschema',
            name='fileName',
            field=models.CharField(default='NAME', max_length=50),
        ),
        migrations.AlterField(
            model_name='filestorageschema',
            name='filePath',
            field=models.FileField(upload_to='F:\\School\\Summer2021\\Independent Study\\media\x0ciles'),
        ),
        migrations.AlterField(
            model_name='filestorageschema',
            name='fileType',
            field=models.CharField(default='TYPE', max_length=50),
        ),
        migrations.AlterField(
            model_name='filestorageschema',
            name='uploadDate',
            field=models.CharField(default='DATE', max_length=50),
        ),
    ]
