# Generated by Django 3.2.4 on 2021-06-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0015_alter_filestorageschema_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorageschema',
            name='fileURL',
            field=models.CharField(default='OOPS', max_length=50),
        ),
    ]
