# Generated by Django 3.2.4 on 2021-06-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0019_alter_filestorageschema_uploadedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorageschema',
            name='uploadedBy',
        ),
    ]
