# Generated by Django 3.2.4 on 2021-06-09 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileStorage', '0020_remove_filestorageschema_uploadedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorageschema',
            name='uploadedBy',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
