# Generated by Django 3.2.4 on 2021-07-09 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='User.member'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='member',
            name='groups',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='User.group'),
            preserve_default='true',
        ),
    ]
