# Generated by Django 3.2.4 on 2021-07-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='leader',
            field=models.BooleanField(default=False),
        ),
    ]
